package com.sunion.core.ble.mfr.entity

class BleDeviceFeature{
    companion object {
        val initTaskList: Array<Triple<TaskCode, String, Set<String>>> = arrayOf(
            Triple(TaskCode.ScanAllBle, "Scan all ble", setOf("1")),
            Triple(TaskCode.ScanUid, "Scan uid", setOf("1")),
            Triple(TaskCode.Connect, "Connect", setOf("1")),
        )

        val modelVersions: Map<String, Set<String>> = mapOf(
            "MFR-TDR01" to setOf("1")
        )

        val taskList: Array<Triple<TaskCode, String, Set<String>>> = arrayOf(
            Triple(TaskCode.AutoTest, "AutoTest", setOf("1")),
            Triple(TaskCode.GetDeviceStatus, "Get deviceStatus", setOf("1")),
            Triple(TaskCode.ToggleLockState, "Toggle lock state", setOf("1")),
            Triple(TaskCode.GetLockSetup, "Get lock setup", setOf("1")),
            Triple(TaskCode.SetSessionKey, "Set session key", setOf("1")),
            Triple(TaskCode.SetPublicUid, "Set public uid", setOf("1")),
            Triple(TaskCode.SetPrivateUid, "Set private uid", setOf("1")),
            Triple(TaskCode.SetRemotePinCodeRandomNumbers, "Set remote pinCode random numbers", setOf("1")),
            Triple(TaskCode.DetermineLockDirection, "Determine lock direction", setOf("1")),
            Triple(TaskCode.AutoUnlockToggleLockState, "Auto unlock toggle lock state", setOf("1")),
            Triple(TaskCode.GetLockTime, "Get lock time", setOf("1")),
            Triple(TaskCode.SetLockTime, "Set lock time", setOf("1")),
            Triple(TaskCode.GetLockTimeZone, "Get lock timeZone", setOf("1")),
            Triple(TaskCode.SetLockTimeZone, "Set lock timeZone", setOf("1")),
            Triple(TaskCode.GetLockConfig, "Get lock config", setOf("1")),
            Triple(TaskCode.ToggleSecurityBolt, "Toggle security bolt", setOf("1")),
            Triple(TaskCode.ToggleGuidingCode, "Toggle guiding code", setOf("1")),
            Triple(TaskCode.ToggleTwoFA, "Toggle twoFA", setOf("1")),
            Triple(TaskCode.ToggleVacationMode, "Toggle vacation mode", setOf("1")),
            Triple(TaskCode.ToggleAutoLock, "Toggle auto lock", setOf("1")),
            Triple(TaskCode.ToggleOperatingSound, "Toggle operating sound", setOf("1")),
            Triple(TaskCode.ToggleKeyPressBeep, "Toggle key press beep", setOf("1")),
            Triple(TaskCode.ToggleShowFastTrackMode, "Toggle show fast track mode", setOf("1")),
            Triple(TaskCode.ToggleSabbathMode, "Toggle sabbath mode", setOf("1")),
            Triple(TaskCode.TogglePhoneticLanguage, "Toggle phonetic language", setOf("1")),
            Triple(TaskCode.TogglePassword, "Toggle password", setOf("1")),
            Triple(TaskCode.ToggleRemotePinCode, "Toggle remote pinCode", setOf("1")),
            Triple(TaskCode.SetBleTx, "Set ble tx", setOf("1")),
            Triple(TaskCode.SetBleAdv, "Set ble adv", setOf("1")),
            Triple(TaskCode.GetEventQuantity, "Get event quantity", setOf("1")),
            Triple(TaskCode.GetEvent, "Get event", setOf("1")),
            Triple(TaskCode.GetBleUserArray, "Get bleUser array", setOf("1")),
            Triple(TaskCode.GetBleUser, "Get bleUser", setOf("1")),
            Triple(TaskCode.AddBleUser, "Add bleUser", setOf("1")),
            Triple(TaskCode.DeleteBleUser, "Delete bleUser", setOf("1")),
            Triple(TaskCode.GetAbility, "Get ability", setOf("1")),
            Triple(TaskCode.GetCredentialArray, "Get credential array", setOf("1")),
            Triple(TaskCode.GetCredential, "Get credential", setOf("1")),
            Triple(TaskCode.AddCode, "Add code", setOf("1")),
            Triple(TaskCode.EditCode, "Edit code", setOf("1")),
            Triple(TaskCode.DeleteCode, "Delete code", setOf("1")),
            Triple(TaskCode.AddFingerprint, "Add fingerprint", setOf("1")),
            Triple(TaskCode.EditFingerprint, "Edit fingerprint", setOf("1")),
            Triple(TaskCode.DeleteFingerprint, "Delete fingerprint", setOf("1")),
            Triple(TaskCode.DeviceGetFingerprint, "Device get fingerprint", setOf("1")),
            Triple(TaskCode.AddFace, "Add face", setOf("1")),
            Triple(TaskCode.EditFace, "Edit face", setOf("1")),
            Triple(TaskCode.DeleteFace, "Delete face", setOf("1")),
            Triple(TaskCode.DeviceGetFace, "Device get face", setOf("1")),
            Triple(TaskCode.GetBlockListArray, "Get blockList array", setOf("1")),
            Triple(TaskCode.GetBlockList, "Get blockList", setOf("1")),
            Triple(TaskCode.AddBlockList, "Add blockList", setOf("1")),
            Triple(TaskCode.DeleteBlockList, "Delete blockList", setOf("1")),
            Triple(TaskCode.GetCredentialHash, "Get credential hash", setOf("1")),
            Triple(TaskCode.GetBleUserHash, "Get bleUser hash", setOf("1")),
            Triple(TaskCode.GetBlacklistHash, "Get blacklist hash", setOf("1")),
            Triple(TaskCode.SetAllDataSynced, "Set all data synced", setOf("1")),
            Triple(TaskCode.SetOTAUpdate, "OTA update", setOf("1")),
            Triple(TaskCode.SetOTACancel, "OTA cancel", setOf("1")),
            Triple(TaskCode.GetRfVersion, "Get RF version", setOf("1")),
            Triple(TaskCode.GetMcuVersion, "Get MCU version", setOf("1")),
            Triple(TaskCode.Restart, "Restart", setOf("1")),
            Triple(TaskCode.FactoryResetSetting, "Factory reset setting", setOf("1")),
            Triple(TaskCode.FactoryResetBlackList, "Factory reset blackList", setOf("1")),
            Triple(TaskCode.FactoryResetPinCode, "Factory reset pinCode", setOf("1")),
            Triple(TaskCode.FactoryReset, "Factory reset", setOf("1")),
            Triple(TaskCode.GetFwVersion, "Get firmware version", setOf("1")),
            Triple(TaskCode.GetFwModel, "Get firmware model", setOf("1")),
            Triple(TaskCode.Disconnect, "Disconnect", setOf("1"))
        )
    }

    enum class TaskCode {
        ScanAllBle,
        ScanUid,
        Connect,
        AutoTest,
        GetDeviceStatus,
        ToggleLockState,
        GetLockSetup,
        SetSessionKey,
        SetPublicUid,
        SetPrivateUid,
        SetRemotePinCodeRandomNumbers,
        DetermineLockDirection,
        AutoUnlockToggleLockState,
        GetLockTime,
        SetLockTime,
        GetLockTimeZone,
        SetLockTimeZone,
        GetLockConfig,
        ToggleSecurityBolt,
        ToggleGuidingCode,
        ToggleTwoFA,
        ToggleVacationMode,
        ToggleAutoLock,
        ToggleOperatingSound,
        ToggleKeyPressBeep,
        ToggleShowFastTrackMode,
        ToggleSabbathMode,
        TogglePhoneticLanguage,
        TogglePassword,
        ToggleRemotePinCode,
        SetBleTx,
        SetBleAdv,
        GetEventQuantity,
        GetEvent,
        GetBleUserArray,
        GetBleUser,
        AddBleUser,
        DeleteBleUser,
        GetAbility,
        GetCredentialArray,
        GetCredential,
        AddCode,
        EditCode,
        DeleteCode,
        AddFingerprint,
        EditFingerprint,
        DeleteFingerprint,
        DeviceGetFingerprint,
        AddFace,
        EditFace,
        DeleteFace,
        DeviceGetFace,
        GetBlockListArray,
        GetBlockList,
        AddBlockList,
        DeleteBlockList,
        GetCredentialHash,
        GetBleUserHash,
        GetBlacklistHash,
        SetAllDataSynced,
        SetOTAUpdate,
        SetOTACancel,
        GetRfVersion,
        GetMcuVersion,
        GetFwVersion,
        GetFwModel,
        Restart,
        FactoryResetSetting,
        FactoryResetBlackList,
        FactoryResetPinCode,
        FactoryReset,
        Disconnect,
        Unknown
    }
}
